# Generated by Django 4.2.7 on 2023-11-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mascota",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("edad", models.IntegerField(verbose_name="Edad")),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Peso"
                    ),
                ),
                ("raza", models.CharField(max_length=100, verbose_name="Raza")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
            ],
        ),
    ]
